apiVersion: v1
kind: Pod
metadata:
  namespace: store
  name: krpclient
  labels:
    app: krpclient
spec:
  containers:
    - name: client
      image: dedovicnermin/krpclient:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /tls
          name: certs
      resources:
        requests:
          cpu: 500m
          memory: 256Mi
  volumes:
    - name: certs
      secret:
        secretName: tls-testadmin
---
apiVersion: v1
kind: Service
metadata:
  name: krpclient-svc
  namespace: store
spec:
  ports:
    - name: external
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: krpclient
  type: ClusterIP


# NOTE: not displayed - ingress controller specifying rule for krpclient.nermdev.io to be routed to the above `service` k8 resource